//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ebookRepository.App.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ebookRepository.App.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DROP TABLE IF EXISTS [FILE_CHECKSUM_MD5];
        ///DROP TABLE IF EXISTS [FILE_CHECKSUM_SHA1];
        ///DROP TABLE IF EXISTS [FILE_CHECKSUM_SHA256];
        ///DROP TABLE IF EXISTS [FILE_DOC];
        ///
        ///DROP TABLE IF EXISTS [FILE_DOC];
        ///CREATE TABLE [FILE_DOC]
        ///(
        ///    [F_CODI] INTEGER       CONSTRAINT [PK_FILE_DOC_F_CODI] PRIMARY KEY ASC ON CONFLICT ROLLBACK AUTOINCREMENT
        ///                           CONSTRAINT [NN_FILE_DOC_F_CODI] NOT NULL        ON CONFLICT ROLLBACK
        ///                           CONSTRAINT [UK_FILE_DOC_F_CODI] UNIQUE         [rest of string was truncated]&quot;;.
        /// </summary>
        public static string DEFAULT_SQL_CREATE_DATABASE {
            get {
                return ResourceManager.GetString("DEFAULT_SQL_CREATE_DATABASE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO [FILE_DOC]([F_NAME], [F_EXTE], [F_SIZE], [F_BYTE], [F_TIME]) VALUES (@F_NAME, @F_EXTE, @F_SIZE, @F_BYTE, @F_TIME);.
        /// </summary>
        public static string DEFAULT_SQL_INSERT_FILE_DOC {
            get {
                return ResourceManager.GetString("DEFAULT_SQL_INSERT_FILE_DOC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO [FILE_CHECKSUM_MD5]   ([FILE_DOC_F_CODI], [CHECKSUM_MD5])    VALUES ((SELECT [F].[F_CODI] FROM [FILE_DOC] AS [F] WHERE [ROWID] = @ROWID), @CHECKSUM_MD5);
        ///INSERT INTO [FILE_CHECKSUM_SHA1]  ([FILE_DOC_F_CODI], [CHECKSUM_SHA1])   VALUES ((SELECT [F].[F_CODI] FROM [FILE_DOC] AS [F] WHERE [ROWID] = @ROWID), @CHECKSUM_SHA1);
        ///INSERT INTO [FILE_CHECKSUM_SHA256]([FILE_DOC_F_CODI], [CHECKSUM_SHA256]) VALUES ((SELECT [F].[F_CODI] FROM [FILE_DOC] AS [F] WHERE [ROWID] = @ROWID), @CHECKSUM_SHA256);
        ///DELETE  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string DEFAULT_SQL_INSERT_FILE_DOC_HASH {
            get {
                return ResourceManager.GetString("DEFAULT_SQL_INSERT_FILE_DOC_HASH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LocalDataStore.
        /// </summary>
        public static string SQLiteDatabasePatch {
            get {
                return ResourceManager.GetString("SQLiteDatabasePatch", resourceCulture);
            }
        }
    }
}
