BEGIN TRANSACTION;

DROP TABLE IF EXISTS [FILE_CHECKSUM_MD5];
DROP TABLE IF EXISTS [FILE_CHECKSUM_SHA1];
DROP TABLE IF EXISTS [FILE_CHECKSUM_SHA256];
DROP TABLE IF EXISTS [FILE_DOC];

DROP TABLE IF EXISTS [FILE_DOC];
CREATE TABLE [FILE_DOC] (
    [COD]  	    INTEGER         CONSTRAINT [PK_FILE_DOC_COD] PRIMARY KEY ASC ON CONFLICT ROLLBACK AUTOINCREMENT
                                CONSTRAINT [NN_FILE_DOC_COD] NOT NULL        ON CONFLICT ROLLBACK
                                CONSTRAINT [UK_FILE_DOC_COD] UNIQUE          ON CONFLICT ROLLBACK
                                CONSTRAINT [CK_FILE_DOC_COD] CHECK ([FILE_DOC].[COD] >= 1),
    [NAME] 	    NVARCHAR (255)  CONSTRAINT [NN_FILE_DOC_NAME]       NOT NULL ON CONFLICT ROLLBACK,
	[FILEBYTE]	BLOB  			CONSTRAINT [NN_FILE_DOC_FILEBYTE] 	NOT NULL ON CONFLICT ROLLBACK,
	[FILEDATE]	DATETIME 		CONSTRAINT [NN_FILE_DOC_DATE] 		NOT NULL ON CONFLICT ROLLBACK
);

DROP TABLE IF EXISTS [FILE_CHECKSUM_MD5];
CREATE TABLE [FILE_CHECKSUM_MD5] (
    [FILE_DOC_COD]  INTEGER      CONSTRAINT [FK_FILE_CHECKSUM_MD5_FILE_DOC_COD] REFERENCES [FILE_DOC](COD)
								 CONSTRAINT [NN_FILE_CHECKSUM_MD5_FILE_DOC_COD] NOT NULL   ON CONFLICT ROLLBACK
								 CONSTRAINT [UK_FILE_CHECKSUM_MD5_FILE_DOC_COD] UNIQUE     ON CONFLICT ROLLBACK,
    [CHECKSUM_MD5] NVARCHAR (32) CONSTRAINT [NN_FILE_CHECKSUM_MD5_CHECKSUM]     NOT NULL   ON CONFLICT ROLLBACK
);

DROP TABLE IF EXISTS [FILE_CHECKSUM_SHA1];
CREATE TABLE [FILE_CHECKSUM_SHA1] (
    [FILE_DOC_COD]  INTEGER       CONSTRAINT [FK_FILE_CHECKSUM_SHA1_FILE_DOC_COD] REFERENCES [FILE_DOC](COD)
								  CONSTRAINT [NN_FILE_CHECKSUM_SHA1_FILE_DOC_COD] NOT NULL   ON CONFLICT ROLLBACK
								  CONSTRAINT [UK_FILE_CHECKSUM_SHA1_FILE_DOC_COD] UNIQUE     ON CONFLICT ROLLBACK,
    [CHECKSUM_SHA1] NVARCHAR (40) CONSTRAINT [NN_FILE_CHECKSUM_SHA1_CHECKSUM] NOT NULL       ON CONFLICT ROLLBACK
);

CREATE TABLE [FILE_CHECKSUM_SHA256] (
    [FILE_DOC_COD]  INTEGER     CONSTRAINT [FK_FILE_CHECKSUM_SHA256_FILE_DOC_COD] REFERENCES [FILE_DOC](COD)
								CONSTRAINT [NN_FILE_CHECKSUM_SHA256_FILE_DOC_COD] NOT NULL   ON CONFLICT ROLLBACK
								CONSTRAINT [UK_FILE_CHECKSUM_SHA256_FILE_DOC_COD] UNIQUE     ON CONFLICT ROLLBACK,
    [CHECKSUM] NVARCHAR (64)	CONSTRAINT [NN_FILE_CHECKSUM_SHA256_CHECKSUM]     NOT NULL   ON CONFLICT ROLLBACK
);

COMMIT TRANSACTION;
